using MasterServerToolkit.Json;
using MasterServerToolkit.MasterServer;

namespace MasterServerToolkit.GameService
{
    /// <summary>
    /// Represents a callback that is invoked when player information changes.
    /// </summary>
    /// <param name="info">The player module that contains the updated player information.</param>
    public delegate void PlayerInfoHandler(IPlayerModule info);

    /// <summary>
    /// Specifies the service account state of a player.
    /// </summary>
    public enum PlayerAccountState
    {
        /// <summary>
        /// The player account is active.
        /// </summary>
        Active = 0,

        /// <summary>
        /// The player account is temporarily suspended.
        /// </summary>
        Suspended = 1,

        /// <summary>
        /// The player account is banned.
        /// </summary>
        Banned = 2,

        /// <summary>
        /// The player account is deleted.
        /// </summary>
        Deleted = 3
    }

    /// <summary>
    /// Specifies the age group reported by the game service.
    /// </summary>
    public enum PlayerAgeGroup
    {
        /// <summary>
        /// The player's age group is unknown.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// The player belongs to a child age group.
        /// </summary>
        Child = 1,

        /// <summary>
        /// The player belongs to a teen age group.
        /// </summary>
        Teen = 2,

        /// <summary>
        /// The player belongs to an adult age group.
        /// </summary>
        Adult = 3
    }

    /// <summary>
    /// Defines the contract for resolving and authenticating a player through the current game service.
    /// </summary>
    public interface IPlayerModule : IServiceModule
    {
        /// <summary>
        /// Gets the current player's service-specific identifier.
        /// </summary>
        string Id { get; }

        /// <summary>
        /// Gets the current player's display name as reported or generated by the service.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Gets the current player's avatar URL or an empty string when no avatar is available.
        /// </summary>
        string Avatar { get; }

        /// <summary>
        /// Gets a value indicating whether the current player identity is a guest identity.
        /// </summary>
        bool IsGuest { get; }

        /// <summary>
        /// Gets a value indicating whether the current service supports platform authentication through <see cref="Authenticate"/>.
        /// </summary>
        /// <remarks>
        /// This value describes only external service authentication, such as Yandex Games authorization or
        /// Itch OAuth. It does not describe regular MST username and password authentication.
        /// </remarks>
        bool IsAuthenticationSupported { get; }

        /// <summary>
        /// Gets the current player's service account state.
        /// </summary>
        PlayerAccountState State { get; }

        /// <summary>
        /// Gets the current player's age group as reported by the service.
        /// </summary>
        PlayerAgeGroup AgeGroup { get; }

        /// <summary>
        /// Gets additional service-specific player data.
        /// </summary>
        MstJson Extra { get; }

        /// <summary>
        /// Occurs when a player authentication attempt completes.
        /// </summary>
        event PlayerInfoHandler OnAuthenticateEvent;

        /// <summary>
        /// Occurs when the resolved player information changes.
        /// </summary>
        event PlayerInfoHandler OnInfoChangedEvent;

        /// <summary>
        /// Authenticates the player with the current game service platform.
        /// </summary>
        /// <param name="callback">The callback to invoke when authentication completes.</param>
        /// <remarks>
        /// Implementations should report failure when <see cref="IsAuthenticationSupported"/> is
        /// <see langword="false"/>. Regular MST username and password login is handled outside this module.
        /// </remarks>
        void Authenticate(SuccessCallback callback);
    }
}
